inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - db/data_schema.rb
    - db/schema.rb
    - node_modules/**/*
    - spec/dummy/db/schema.rb
  TargetRubyVersion: 2.5

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Metrics/AbcSize:
#   Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 250

# Metrics/CyclomaticComplexity:
#   Max: 10

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 50

# Metrics/PerceivedComplexity:
#   Max: 10

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Will report offences for many places that are much more readable without using a guard clause
Style/GuardClause:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true
  Enabled: true
